### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by anton-k** [hexresearch/hschain-utxo#44]
- [x] Design language of smartcontracts
- [x] Implement sigma-protocols
- [x] Implement type-checker for the language
- [x] Impement state transitions for UTXO-model and design protocol of transactions
- [x] Implement language-tooling for the user: compiler, REPL, API-client
- [x] Design low-level representation of the language for efficient evaluation
- [x] Implement efficient evaluation of low-level language
- [x] Integrate language with PoS version of hschain
- [x] Build node with API to post TXs and interact with blockchain
- [x] Build test environment for simple scenarios  as examples described in Ergo script
- [x] Prototype of the compiler
- [x] Online documentation of the language and internal documentation
- [x] Implenment stable builds with Nix
- [x] Add CI for the project
- [x] Compilation of high-level language
- [x] Integrate G-machine based scheme of language compilation to the CLI-utility (hschain-utxo-compiler)
- [ ] Update REPL for transition to execution on low-level language
- [ ] Integrate with PoW version of hschain
- [ ] Add TX with library functions (see how it's made in Ergo)
- [ ] Redesign node for PoW
- [ ] Update language and implementation for PoW
- [ ] Efficiency tests of language evaluation
- [ ] Correctness tests of language evaluation
- [ ] Stress tests of web-node
- [ ] Involved scenarios of the usage like crowd-funding, Ponzi scheme
- [ ] Tests on real nodes
- [ ] Security audit 
- [ ] Open source the packages
- [ ] Implement common Bitcoin contracts as in sources
       * https://www.oreilly.com/library/view/mastering-bitcoin/9781491902639/ch05.html#:~:text=The%20five%20standard%20types%20of,detail%20in%20the%20following%20sections
       * https://en.bitcoin.it/wiki/Script#Script_examples
      * Key names for contracts: Pay-to-script-hash, Multisitg, Time lock, Hash lock, Data output
 - [ ] Reference interpreter for core language. It is language which is interpreted by nodes and its semantics it most important for blockchain
